### ISSUE TITLE
Status request

### ISSUE THREAD

**Issue by Mufasa** [jankeesvanandel/cascading-release-maven-plugin#9]
Hi, I was just wondering whether this project actually works and whether or not you are still maintaining it.

Thanks in advance.

**Comment by jankeesvanandel** [comment]
Hi, Yes it works. I've used it on my own project. But it's definitely not guaranteed to work on your project, since it's a bit sensitive to your project structure and your internal dependencies.

I'm not actively maintaining it anymore, since I moved to Scala and SBT...
